title: Stel de pinnen in voor twee zoemers
hero_image: images/banner.png
description: Hoe kan je de pinnen voor twee zoemers op je Raspberry Pi Pico instellen
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Stel de pinnen in voor twee zoemers
