title: Set the pins for two buzzers
hero_image: images/banner.png
description: multiple-buzzer-pins description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
