
title: Définir les broches pour deux buzzers
hero_image: images/banner.png
description: Comment définir les broches pour deux buzzers sur un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-17"
steps:
  - title: Définir les broches pour deux buzzers
